/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author fernando.francisco
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskPainel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnarquivos = new javax.swing.JMenu();
        mnarquivosclientes = new javax.swing.JMenuItem();
        mnarquivosprodutos = new javax.swing.JMenuItem();
        mnarquivosusuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnarquivosaltsenha = new javax.swing.JMenuItem();
        mnarquivosaltusuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnarquivossair = new javax.swing.JMenuItem();
        mnmovimentos = new javax.swing.JMenu();
        mnmovimentosvendas = new javax.swing.JMenuItem();
        mnmovimentosrelvendas = new javax.swing.JMenuItem();
        mnajuda = new javax.swing.JMenu();
        mnajudasobre = new javax.swing.JMenuItem();
        mnajudaajuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DeskPainel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout DeskPainelLayout = new javax.swing.GroupLayout(DeskPainel);
        DeskPainel.setLayout(DeskPainelLayout);
        DeskPainelLayout.setHorizontalGroup(
            DeskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        DeskPainelLayout.setVerticalGroup(
            DeskPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        mnarquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/application.png"))); // NOI18N
        mnarquivos.setText("Arquivos");

        mnarquivosclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/user_suit.png"))); // NOI18N
        mnarquivosclientes.setText("Clientes");
        mnarquivos.add(mnarquivosclientes);

        mnarquivosprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/page_white_paste.png"))); // NOI18N
        mnarquivosprodutos.setText("Produtos");
        mnarquivos.add(mnarquivosprodutos);

        mnarquivosusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/user.png"))); // NOI18N
        mnarquivosusuarios.setText("Usuários");
        mnarquivosusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosusuariosActionPerformed(evt);
            }
        });
        mnarquivos.add(mnarquivosusuarios);
        mnarquivos.add(jSeparator1);

        mnarquivosaltsenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/pencil_go.png"))); // NOI18N
        mnarquivosaltsenha.setText("Alterar Senha");
        mnarquivos.add(mnarquivosaltsenha);

        mnarquivosaltusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/user_edit.png"))); // NOI18N
        mnarquivosaltusuario.setText("Alterar Usuário");
        mnarquivosaltusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnarquivosaltusuarioActionPerformed(evt);
            }
        });
        mnarquivos.add(mnarquivosaltusuario);
        mnarquivos.add(jSeparator2);

        mnarquivossair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/exclamation.png"))); // NOI18N
        mnarquivossair.setText("Sair");
        mnarquivos.add(mnarquivossair);

        jMenuBar1.add(mnarquivos);

        mnmovimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/page.png"))); // NOI18N
        mnmovimentos.setText("Movimentos");

        mnmovimentosvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/money.png"))); // NOI18N
        mnmovimentosvendas.setText("Vendas");
        mnmovimentosvendas.setToolTipText("");
        mnmovimentos.add(mnmovimentosvendas);

        mnmovimentosrelvendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/page_excel.png"))); // NOI18N
        mnmovimentosrelvendas.setText("Relatórios Vendas");
        mnmovimentosrelvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnmovimentosrelvendasActionPerformed(evt);
            }
        });
        mnmovimentos.add(mnmovimentosrelvendas);

        jMenuBar1.add(mnmovimentos);

        mnajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/find.png"))); // NOI18N
        mnajuda.setText("Ajuda");

        mnajudasobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/information.png"))); // NOI18N
        mnajudasobre.setText("Sobre");
        mnajuda.add(mnajudasobre);

        mnajudaajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/help.png"))); // NOI18N
        mnajudaajuda.setText("Ajuda");
        mnajuda.add(mnajudaajuda);

        jMenuBar1.add(mnajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskPainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnmovimentosrelvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnmovimentosrelvendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnmovimentosrelvendasActionPerformed

    private void mnarquivosaltusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosaltusuarioActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mnarquivosaltusuarioActionPerformed

    private void mnarquivosusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnarquivosusuariosActionPerformed
        // TODO add your handling code here:
          frmUsuarios usuarios = new frmUsuarios();
        DeskPainel.add(usuarios);
        usuarios.show();
    }//GEN-LAST:event_mnarquivosusuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskPainel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnajuda;
    private javax.swing.JMenuItem mnajudaajuda;
    private javax.swing.JMenuItem mnajudasobre;
    private javax.swing.JMenu mnarquivos;
    private javax.swing.JMenuItem mnarquivosaltsenha;
    private javax.swing.JMenuItem mnarquivosaltusuario;
    private javax.swing.JMenuItem mnarquivosclientes;
    private javax.swing.JMenuItem mnarquivosprodutos;
    private javax.swing.JMenuItem mnarquivossair;
    private javax.swing.JMenuItem mnarquivosusuarios;
    private javax.swing.JMenu mnmovimentos;
    private javax.swing.JMenuItem mnmovimentosrelvendas;
    private javax.swing.JMenuItem mnmovimentosvendas;
    // End of variables declaration//GEN-END:variables
}
