/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author alexe
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codUsuario = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        sobrenome = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        confirmaSenha = new javax.swing.JPasswordField();
        perfil = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmdAnterior = new javax.swing.JButton();
        cmdPrimeiro = new javax.swing.JButton();
        cmdProximo = new javax.swing.JButton();
        cmdUltimo = new javax.swing.JButton();
        cmdAdicionar = new javax.swing.JButton();
        cmdEditar = new javax.swing.JButton();
        cmdSalvar = new javax.swing.JButton();
        cmdProcurar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Usuários");
        setEnabled(false);

        jLabel1.setText("Cod. Usuário:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmar senha:");

        codUsuario.setEnabled(false);

        nome.setEnabled(false);

        sobrenome.setEnabled(false);

        senha.setEnabled(false);

        confirmaSenha.setEnabled(false);

        perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um perfil", "Administrador", "Funcionário" }));
        perfil.setEnabled(false);

        jLabel6.setText("Perfil:");

        cmdAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/control_rewind_blue.png"))); // NOI18N
        cmdAnterior.setToolTipText("Cadastro anterior");

        cmdPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/control_start_blue.png"))); // NOI18N
        cmdPrimeiro.setToolTipText("Primeiro cadastro");

        cmdProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/control_fastforward_blue.png"))); // NOI18N
        cmdProximo.setToolTipText("Cadstro próximo");

        cmdUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/control_end_blue.png"))); // NOI18N
        cmdUltimo.setToolTipText("Último cadastro");

        cmdAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/add.png"))); // NOI18N
        cmdAdicionar.setToolTipText("Adicionar usuário");
        cmdAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdicionarActionPerformed(evt);
            }
        });

        cmdEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/pencil.png"))); // NOI18N
        cmdEditar.setToolTipText("Editar usuário");

        cmdSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/database_save.png"))); // NOI18N
        cmdSalvar.setToolTipText("Salvar usuário");
        cmdSalvar.setEnabled(false);
        cmdSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalvarActionPerformed(evt);
            }
        });

        cmdProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/magnifier.png"))); // NOI18N
        cmdProcurar.setToolTipText("Procurar usuário");

        cmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons/delete.png"))); // NOI18N
        cmdCancelar.setToolTipText("Cancela a operação");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(sobrenome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(senha, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(confirmaSenha))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdProximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUltimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdProcurar)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmdEditar)
                                    .addComponent(cmdUltimo)
                                    .addComponent(cmdProximo)
                                    .addComponent(cmdPrimeiro)
                                    .addComponent(cmdAnterior)
                                    .addComponent(cmdAdicionar))
                                .addComponent(cmdCancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(cmdSalvar)))
                    .addComponent(cmdProcurar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdicionarActionPerformed
        
        cmdPrimeiro.setEnabled(false);
        cmdAnterior.setEnabled(false);
        cmdProximo.setEnabled(false);
        cmdUltimo.setEnabled(false);
        cmdEditar.setEnabled(false);
        cmdProcurar.setEnabled(false);
        cmdAdicionar.setEnabled(false);
        cmdCancelar.setEnabled(true);
        cmdSalvar.setEnabled(true);
        
        codUsuario.setEnabled(true);
        nome.setEnabled(true);
        sobrenome.setEnabled(true);
        senha.setEnabled(true);
        confirmaSenha.setEnabled(true);
        perfil.setEnabled(true);
        
        codUsuario.setText("");
        nome.setText("");
        sobrenome.setText("");
        senha.setText("");
        confirmaSenha.setText("");
        perfil.setSelectedIndex(0);
        
        codUsuario.requestFocusInWindow();
    }//GEN-LAST:event_cmdAdicionarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        
        cmdPrimeiro.setEnabled(true);
        cmdAnterior.setEnabled(true);
        cmdProximo.setEnabled(true);
        cmdUltimo.setEnabled(true);
        cmdEditar.setEnabled(true);
        cmdProcurar.setEnabled(true);
        cmdAdicionar.setEnabled(true);
        cmdCancelar.setEnabled(false);
        cmdSalvar.setEnabled(false);
        
        codUsuario.setEnabled(false);
        nome.setEnabled(false);
        sobrenome.setEnabled(false);
        senha.setEnabled(false);
        confirmaSenha.setEnabled(false);
        perfil.setEnabled(false);
        
        codUsuario.setText("");
        nome.setText("");
        sobrenome.setText("");
        senha.setText("");
        confirmaSenha.setText("");
        perfil.setSelectedIndex(0);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalvarActionPerformed
        
        cmdPrimeiro.setEnabled(true);
        cmdAnterior.setEnabled(true);
        cmdProximo.setEnabled(true);
        cmdUltimo.setEnabled(true);
        cmdEditar.setEnabled(true);
        cmdProcurar.setEnabled(true);
        cmdAdicionar.setEnabled(true);
        cmdCancelar.setEnabled(false);
        cmdSalvar.setEnabled(false);
        
        codUsuario.setEnabled(false);
        nome.setEnabled(false);
        sobrenome.setEnabled(false);
        senha.setEnabled(false);
        confirmaSenha.setEnabled(false);
        perfil.setEnabled(false);
        
    }//GEN-LAST:event_cmdSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdicionar;
    private javax.swing.JButton cmdAnterior;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEditar;
    private javax.swing.JButton cmdPrimeiro;
    private javax.swing.JButton cmdProcurar;
    private javax.swing.JButton cmdProximo;
    private javax.swing.JButton cmdSalvar;
    private javax.swing.JButton cmdUltimo;
    private javax.swing.JTextField codUsuario;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nome;
    private javax.swing.JComboBox<String> perfil;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField sobrenome;
    // End of variables declaration//GEN-END:variables
}
